import { Exo_2 } from 'next/font/google'
import './styles/style.css'
import Navbar from './components/Navbar'

const exo_2 = Exo_2({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={exo_2.className}>
        <Navbar />
        {children}</body>
    </html>
  )
}
